import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className="videoDiv">
              <video autoPlay muted loop id="myVideo" className="backgroundVideo">
                  <source src="/fisennebackground.mp4" type="video/mp4"/>
              </video>
          </div>

          <span className="filigreeTop">
              <h1 >La ferme du château</h1>
          </span>
          <span className="filigreeBottom">
              <h1>de Fisenne</h1>
          </span>
          <span className="borderTop"/>
          <span className="borderRight"/>
          <span className="borderBottom"/>
          <span className="borderLeft"/>
          <p className="heroLabel">
              La ferme du château de Fisenne
          </p>
          <button className="waxButton">découvrez le château</button>
          <p className="heroAnno">
              Anno 1785
          </p>
          <Image src="/castle.svg" width={10} height={10}/>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
